//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlyrapphim
{
    using System;
    using System.Collections.Generic;
    
    public partial class phim2d
    {
        public string Madon { get; set; }
        public Nullable<double> Phuthughedoi { get; set; }
    
        public virtual quanlyphim quanlyphim { get; set; }
    }
}
