//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlyrapphim
{
    using System;
    using System.Collections.Generic;
    
    public partial class quanlyphim
    {
        public string Madon { get; set; }
        public string Tenphim { get; set; }
        public string Quocgia { get; set; }
        public string Theloai { get; set; }
        public Nullable<System.DateTime> Ngaycongchieu { get; set; }
        public Nullable<int> Dotuoiquidinh { get; set; }
    
        public virtual phim2d phim2d { get; set; }
        public virtual phim3d phim3d { get; set; }
    }
}
